name: Setup Hub Instance
description: Extract and start tackle2-hub from container with entities

inputs:
  hub_image:
    description: 'Hub container image URL (without tag)'
    required: false
    default: 'quay.io/konveyor/tackle2-hub'
  hub_tag:
    description: 'Hub container image tag'
    required: false
    default: 'latest'

outputs:
  hub_url:
    description: 'Hub base URL'
    value: ${{ steps.set-outputs.outputs.hub_url }}
  hub_pid:
    description: 'Hub process ID'
    value: ${{ steps.set-outputs.outputs.hub_pid }}

runs:
  using: composite
  steps:
    - name: Extract hub from container
      shell: bash
      run: |
        echo "Extracting hub from ${{ inputs.hub_image }}:${{ inputs.hub_tag }}..."

        # Pull hub container image
        docker pull ${{ inputs.hub_image }}:${{ inputs.hub_tag }}

        # Create temporary container
        docker create --name hub-extract ${{ inputs.hub_image }}:${{ inputs.hub_tag }}

        # Extract hub binary
        mkdir -p "$RUNNER_TEMP/hub-bin"
        docker cp hub-extract:/usr/bin/hub "$RUNNER_TEMP/hub-bin/hub"
        chmod +x "$RUNNER_TEMP/hub-bin/hub"

        # Cleanup container
        docker rm hub-extract

        echo "Hub binary extracted successfully"
        "$RUNNER_TEMP/hub-bin/hub" version || echo "Hub binary ready"

    - name: Start hub in background
      shell: bash
      env:
        DISCONNECTED: 1
        HUB_BASE_URL: localhost:8080
      run: |
        export DB_PATH="$RUNNER_TEMP/hub.db"
        rm -f "$DB_PATH"
        echo "Starting hub..."
        echo "Environment: DB_PATH=$DB_PATH, DISCONNECTED=$DISCONNECTED, HUB_BASE_URL=$HUB_BASE_URL"
        "$RUNNER_TEMP/hub-bin/hub" > "$RUNNER_TEMP/hub.log" 2>&1 &
        HUB_PID=$!
        echo "HUB_PID=$HUB_PID" >> $GITHUB_ENV
        echo "Hub started with PID: $HUB_PID"

        # Save PID to file for cleanup
        echo $HUB_PID > "$RUNNER_TEMP/hub.pid"

    - name: Wait for hub to be ready
      shell: bash
      run: |
        echo "Waiting for hub to start..."
        CURL_OPTS=(--fail --silent --show-error --connect-timeout 3 --max-time 15)
        for i in {1..30}; do
          if curl "${CURL_OPTS[@]}" http://localhost:8080/applications > /dev/null; then
            echo "Hub is ready!"
            break
          fi
          echo "Attempt $i: Hub not ready yet, waiting..."
          sleep 2
        done

        # Verify hub is accessible
        if ! curl "${CURL_OPTS[@]}" http://localhost:8080/applications > /dev/null; then
          echo "ERROR: Hub failed to start"
          echo "Hub logs:"
          cat "$RUNNER_TEMP/hub.log" || true
          exit 1
        fi

    - name: Create hub entities
      shell: bash
      env:
        HUB_BASE_URL: localhost:8080
      run: |
        chmod +x ${{ github.workspace }}/scripts/create-entities.sh
        ${{ github.workspace }}/scripts/create-entities.sh

    - name: Set outputs
      id: set-outputs
      shell: bash
      run: |
        echo "hub_url=http://localhost:8080" >> $GITHUB_OUTPUT
        echo "hub_pid=$HUB_PID" >> $GITHUB_OUTPUT
        echo "HUB_BASE_URL=http://localhost:8080" >> $GITHUB_ENV

    - name: Display hub info
      shell: bash
      run: |
        echo "============================================"
        echo "Hub Instance Ready"
        echo "============================================"
        echo "Hub URL: http://localhost:8080"
        echo "Hub PID: $HUB_PID"
        echo "Database: $RUNNER_TEMP/hub.db"
        echo "============================================"
