name: PR/push CLI tests for main

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**.md'

jobs:
  test-suite:
    uses: ./.github/workflows/test-suite-java-containerless.yaml
    secrets:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    with:
      tag: latest
      # TODO: Add other provider tests
      test_path: tests/analysis/java
