name: Cleanup Hub Instance
description: Stop and cleanup hub instance

runs:
  using: composite
  steps:
    - name: Stop hub process
      if: always()
      shell: bash
      run: |
        echo "Stopping hub instance..."
        PID_FILE="${{ runner.temp }}/hub.pid"
        if [ -f "$PID_FILE" ]; then
          HUB_PID=$(cat "$PID_FILE")
          if ps -p $HUB_PID > /dev/null 2>&1; then
            echo "Killing hub process $HUB_PID"
            kill $HUB_PID || true
            sleep 2
            # Force kill if still running
            if ps -p $HUB_PID > /dev/null 2>&1; then
              echo "Force killing hub process $HUB_PID"
              kill -9 $HUB_PID || true
            fi
          else
            echo "Hub process $HUB_PID not running"
          fi
        else
          echo "No hub PID file found at $PID_FILE"
        fi

    - name: Show hub logs on failure
      if: failure()
      shell: bash
      run: |
        echo "============================================"
        echo "Hub Logs"
        echo "============================================"
        cat "${{ runner.temp }}/hub.log" || echo "No hub logs found"

    - name: Cleanup hub files
      if: always()
      shell: bash
      run: |
        echo "Cleaning up hub files..."
        rm -f "${{ runner.temp }}/hub.pid" "${{ runner.temp }}/hub.db" "${{ runner.temp }}/hub.log" || true
        rm -rf "${{ runner.temp }}/tackle2-hub" || true
